### ISSUE TITLE
Not Matching chip ID's

### ISSUE THREAD

**Issue by abush901** [adafruit/Adafruit_LSM6DS#13]
Thank you for opening an issue on an Adafruit Arduino library repository.  To
improve the speed of resolution please review the following guidelines and
common troubleshooting steps below before creating the issue:

- Arduino board:  **INSERT ARDUINO BOARD NAME/TYPE HERE**
LSM6DSOX
- Arduino IDE version (found in Arduino -> About Arduino menu):  **INSERT ARDUINO
  VERSION HERE**
1.8.13
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**
The Problem occuring is that the board ID that is being read and the board ID that needs to be matched are not the same which is causing the example code given to run incorrectly, any solutions?

**Comment by siddacious** [comment]
Please give more information:
* Which brand and model of microcontroller are you using
* What specific brand and model of sensor are you using?
* Which exact example code are you trying to run
* What chip ID is being read?

If the chip ID is not matching, you are most likely using the wrong class for the sensor.
