### ISSUE TITLE
what power mode is used by default / how to switch between power modes

### ISSUE THREAD

**Issue by jerabaul29** [adafruit/Adafruit_LSM6DS#20]
The datasheet for the LSM6DSOX mentions several power modes (section 6.2 Accelerometer power modes and 6.3 Gyroscope power mode).

- what power mode is enabled by default? Is it the high performance? Other?
- any way to switch between the power modes?

**Comment by ladyada** [comment]
we dont' have power mode support - we use default

**Comment by jerabaul29** [comment]
Ok. Any hints how to add? That would be helpful to have.
